---
title: "Tabela de ações"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyquant)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)

prices <- read.csv("C:/Users/Carvalho/Documents/R Projects/ativos/bolsadeacoes/prices.csv") %>% 
  mutate(date = as.Date(date))
tabela_periodo <- data.frame(periodo =c("1M","6M","1A","10A"), dias = c(30,180,365,3600))
cores <- c("PETR3"="green","ITUB4"="blue","ABEV3"="yellow","BBDC3"="brown","WEGE3"="red","SANB11"="orange","RDOR3"="pink","BBAS3"="purple")
```

Column {.sidebar}
---------------------
###
```{r}
selectInput("acao", label="Escolha a ação",
            choices = c("PETR3","ITUB4","ABEV3","BBDC3","WEGE3","SANB11","RDOR3","BBAS3"))
selectInput("periodo", label = "Escolha o periodo",
            choices = c("1M","6M","1A","1OA"))
```
Rows {data-width=650}
-----------------------------------------------------------------------

### Tendencias

```{r}
renderPlotly({
  periodo <-  Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>% 
    filter(date >=periodo, symbol == input$acao) %>% 
    ggplot()+
    aes(x= date, y = adjusted,color= symbol)+
    geom_line()+
    scale_color_manual(values = cores)+
    labs(x = "", y= "Cotação")+
    ggtitle(label = input$acao)+
    theme(
      panel.background = element_blank(), plot.title = element_text(size=22),
      legend.position = "none"
    )
    
})

```

### Todas as tendencias
```{r}
renderPlotly({
  periodo <-  Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
prices %>% 
  filter(date>=periodo) %>% 
  ggplot()+
  aes(x = date, y =adjusted, color = symbol)+
  geom_line(size = 1.1)+
  labs(x="",y="Cotação",color ="Ação")+
  theme(panel.background = element_blank())
})
```

Rows {data-width=350}
-----------------------------------------------------------------------

### Cotação 

```{r}
renderDataTable({
  periodo <-  Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
prices %>% 
  filter(date>=periodo,symbol ==input$acao) %>% 
  mutate(across(where(is.double),round,digits = 2)) %>% 
  arrange(desc(date)) %>% 
  rename(
    Ação = symbol,
    Data = date,
    Abertura = open,
    Máximo = high,
    Mínimo = low,
    Fechamento = close,
    Volume = volume,
    Ajustado = adjusted
  ) %>% 
  datatable(rownames = FALSE)
})

```



